FROM python:3.7-slim

RUN mkdir -p /app

WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt

COPY ./src/ /app/
ENV FLASK_APP=inference.py

CMD flask run -h 0.0.0.0 -p 5000