apiVersion: apps/v1
kind: Deployment
metadata:
  name: mv-ml-deploy
  labels:
    app: mv-ml-kube-deploy
spec:
  selector:
    matchLabels:
      app: mv-ml-kube-deploy
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mv-ml-kube-deploy
    spec:
      containers:
      - name: mv-ml-kube-deploy
        image: upendra318/mv-ml-kubernetes-deploy-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
    resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "500m"
     