apiVersion: v1
kind: Service
metadata:
  name: ml-service
  labels:
    app: mv-ml-kube-deploy
spec:
  type: NodePort #NodePort for local/  LoadBalancer for production
  selector:
    app: mv-ml-kube-deploy
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000